### ISSUE TITLE
is it possible to do something with a quest one on build 49xxxxxxxxxxxx? 

### ISSUE THREAD

**Issue by leandrofriedrich** [darknight1050/quest-bootloader-unlocker#1]
Hi, i have recently found this project and i was wondering if theres something one can do on a quest 1 running build 49845030369000410? do you know if said vuln is patched in that version? or is there anything else interesting for this?

**Comment by darknight1050** [comment]
Latest unpatched version is 16476800119700000, for newer versions you'd need to find a different vulnerability/method to unlock it.

**Comment by leandrofriedrich** [comment]
mmm, sad
and we cant downgrade it right?

**Comment by darknight1050** [comment]
As far as I know it's not possible to downgrade to such an old version.
