### ISSUE TITLE
"Can't find the Fastboot Device!" Error

### ISSUE THREAD

**Issue by patheticallyemma** [darknight1050/quest-bootloader-unlocker#3]
I'm getting the "Can't find the Fastboot Device!" error for some reason. I'm guessing I'm missing something. I'm using a Meta Quest 2. I have it in Fastboot mode and it shows "Fastbootd". I think I'm just missing something, so I have some very basic questions.

Was this patched/does it not work anymore?
What exactly are the steps here?
Am I in the wrong "fastboot" mode?
Do I have the wrong Quest 2 for it to be supported?
Do I need to downgrade my OS?
Do I need to download a specific driver for my device?
Do I need to extract my bootloader binary first and patch it? Or
Do I download one from the internet and run the OTA payload extractor? If so,
Is there a specific OTA payload.bin I should download to not mess up my headset? If so,
Can I get a link to it?

S/N: 1WMHHB41EJ2236
Product name: hollywood
Secure boot: yes
HW version: 0
Bootloader version: unknown
OS Version: SQ3A.220605.009.A1

**Comment by darknight1050** [comment]
As the README says this is patched and only works on old firmware (till May 9 2021).

You can check the version of your quest with `fastboot oem device-info`. It will be under `Build number:`. 
You can't downgrade your OS.
You might need a driver for it, just checkout some tutorial for getting fastboot to work. 
You need to extract the bootloader from the firmware update (the same version your quest is on). Checkout the README for the tools used. [You can download it here](https://cocaine.trade/). If `Patches.cs` doesn't contain your version you'd need to either add the patches there yourself or upgrade to a supported firmware (sideload the update). 
You can text me on discord @darknight1050 if you still have problems getting it to work.

If you are worried about messing up your headset don't do this. You can completely brick your headset.
